/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Iris session bound to a reference or foreign adapter. */
export declare class MemorySession {
  constructor()
  executeVos(source: string, parametersJson?: string | undefined | null): ExecuteResult
  /** Execute a structured Iris operation JSON payload (generated client ABI). */
  executeOperation(operationJson: string): ExecuteResult
  /** Apply managed-push schema to a SQLite session (`:memory:` or file path). */
  managedPush(schema: string): void
  close(): void
}

/** Parse and validate schema source (same semantics as `iris-tools check`). */
export declare function checkSource(source: string): CheckSourceResult

/** Result of validating a VOS / `.iris` schema source via the Rust core. */
export interface CheckSourceResult {
  ok: boolean
  tableCount: number
  schemaFingerprint: string
  generatorVersion: string
  error?: string
}

/** Execute VOS against the bound adapter. */
export interface ExecuteResult {
  ok: boolean
  /** JSON array of row objects. */
  rowsJson: string
  error?: string
}

/** Codegen output summary. */
export interface GenerateResult {
  ok: boolean
  outputPath: string
  schemaFingerprint: string
  error?: string
}

/** Generate Rust domain bindings (same as `iris-tools generate --target rust`). */
export declare function generateRust(source: string, outDir: string): GenerateResult

/** Read-only schema introspection JSON (`GenerationModel` shape). */
export declare function introspectSchema(source: string): string

/** Library version (matches `iris::version()` / Cargo package version). */
export declare function irisVersion(): string

/** Load `iris.von` from a config path. */
export declare function loadProject(configPath: string): LoadProjectResult

/** Loaded on-disk project metadata. */
export interface LoadProjectResult {
  root: string
  config: string
  schemaGlob: string
}

/** Plan a managed-push migration (same as `iris-tools migrate plan`). */
export declare function migratePlanCmd(configPath: string, source: string, outDir?: string | undefined | null): MigratePlanResult

/** Migration plan summary. */
export interface MigratePlanResult {
  ok: boolean
  planPath: string
  error?: string
}

/** Open an in-memory reference session. */
export declare function openMemorySession(): MemorySession

/** Open a MySQL session from a connection URL. */
export declare function openMysqlSession(url: string): MemorySession

/** Open a PostgreSQL session from a connection URL. */
export declare function openPostgresSession(url: string): MemorySession

/** Open a session for a datasource declared in `iris.von`. */
export declare function openProjectSession(configPath: string, source: string): MemorySession

/** Open a session for the requested adapter profile. */
export declare function openSession(options?: OpenSessionOptions | undefined | null): MemorySession

/** Session open options (unified N-API entry). */
export interface OpenSessionOptions {
  /** `memory` | `sqlite` | `postgres` | `mysql` | `project` */
  profile?: string
  sqlitePath?: string
  postgresUrl?: string
  mysqlUrl?: string
  projectConfig?: string
  datasource?: string
}

/** Open a SQLite session on a filesystem path or `:memory:`. */
export declare function openSqliteSession(path: string): MemorySession

/** Read merged schema text for a loaded project. */
export declare function readSchema(projectRoot: string, schemaGlob: string): string
