/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Parse and validate schema source (same semantics as `iris-tools check`). */
export declare function checkSource(source: string): CheckSourceResult;

/** Result of validating a VOS / `.iris` schema source via the Rust core. */
export interface CheckSourceResult {
    ok: boolean;
    tableCount: number;
    schemaFingerprint: string;
    generatorVersion: string;
    error?: string;
}

/** Library version (matches `iris::version()` / Cargo package version). */
export declare function irisVersion(): string;
