[package]
name = "iris-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Browser WebAssembly binding for Iris ORM"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
iris = { workspace = true }
iris-generator = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
iris = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
