//! Phase 8: Dejavu generation golden + determinism.

use iris_generator::{GenerationModel, TEMPLATE_NAMES, emit_rust_domain, prefers_aot};

const USER_SCHEMA: &str = r#"
table User {
    @@user_id: utf8,
    @user_name: utf8,
    active: bool,
}
"#;

#[test]
fn prefers_aot_by_default() {
    assert!(prefers_aot());
    assert!(TEMPLATE_NAMES.contains(&"domain_mod"));
    assert!(TEMPLATE_NAMES.contains(&"file_header"));
}

#[test]
fn generation_model_from_vos_is_deterministic() {
    let a = GenerationModel::from_vos_schema(USER_SCHEMA).unwrap();
    let b = GenerationModel::from_vos_schema(USER_SCHEMA).unwrap();
    assert_eq!(a, b);
    assert_eq!(a.tables.len(), 1);
    assert_eq!(a.tables[0].name, "User");
    assert!(a.tables[0].fields.iter().any(|f| f.primary));
    assert!(
        a.tables[0]
            .fields
            .iter()
            .any(|f| f.name == "active" && f.rust_ty == "bool")
    );
}

#[test]
fn rust_emit_contains_structs_fingerprint_and_no_sql() {
    let model = GenerationModel::from_vos_schema(USER_SCHEMA).unwrap();
    let out = emit_rust_domain(&model).unwrap();
    assert!(out.contains("Generated by Iris"));
    assert!(out.contains("pub struct User"));
    assert!(out.contains("pub user_id: String"));
    assert!(out.contains("pub active: bool"));
    assert!(out.contains("SCHEMA_FINGERPRINT"));
    assert!(out.contains("UUID_FIELDS"));
    assert!(out.contains("pub struct Db"));
    assert!(out.contains("pub struct Txn"));
    assert!(out.contains("fn find_many"));
    assert!(out.contains("fn with_rollback"));
    assert!(out.contains("fn query"));
    assert!(out.contains("UserWhere"));
    assert!(out.contains(".filter(x =>"));
    assert!(!out.contains("SELECT "));
    assert!(!out.contains("CREATE TABLE"));
    let again = emit_rust_domain(&model).unwrap();
    assert_eq!(out, again);
}

#[test]
fn rust_emit_optional_types_are_not_html_escaped() {
    let schema = r#"
table Item {
    @@id: utf8,
    note: utf8?,
}
"#;
    let model = GenerationModel::from_vos_schema(schema).unwrap();
    let out = emit_rust_domain(&model).unwrap();
    assert!(out.contains("Option<String>"));
    assert!(!out.contains("&lt;"));
}

#[test]
fn rust_emit_uuid_fields_table() {
    let schema = r#"
table Item {
    @@id: uuid,
    owner_id: uuid?,
    name: utf8,
}
"#;
    let model = GenerationModel::from_vos_schema(schema).unwrap();
    assert!(model.tables[0].fields.iter().any(|f| f.name == "id" && f.is_uuid));
    assert!(
        model.tables[0]
            .fields
            .iter()
            .any(|f| f.name == "owner_id" && f.is_uuid && f.optional)
    );
    let out = emit_rust_domain(&model).unwrap();
    assert!(out.contains(r#"("Item", "id")"#));
    assert!(out.contains(r#"("Item", "owner_id")"#));
    assert!(!out.contains(r#"("Item", "name")"#));
}

#[test]
fn write_rust_domain_atomic() {
    let dir = std::env::temp_dir().join(format!(
        "iris-gen-{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    let model = GenerationModel::from_vos_schema(USER_SCHEMA).unwrap();
    let paths = iris_generator::write_rust_domain(&model, &dir).unwrap();
    let root = dir.join("generated/iris/rust");
    assert_eq!(paths.len(), 5);
    assert!(paths.iter().all(|p| p.starts_with(&root)));
    assert!(root.join("mod.rs").is_file());
    assert!(root.join("models.rs").is_file());
    assert!(root.join("operations.rs").is_file());
    assert!(root.join("metadata.rs").is_file());
    assert!(root.join("errors.rs").is_file());
    let text = std::fs::read_to_string(root.join("models.rs")).unwrap();
    assert!(text.contains("pub struct User"));
    let ops = std::fs::read_to_string(root.join("operations.rs")).unwrap();
    assert!(ops.contains("pub struct Db"));
    let _ = std::fs::remove_dir_all(dir);
}
